import { Bell, Mail, MessageSquare, RefreshCw } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { DataTable, type Column } from "@/components/common/DataTable";
import { StatCard } from "@/components/common/StatCard";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Button } from "@/components/ui/button";
import { useList } from "@/hooks/use-crud";

interface NotificationLogRow {
  id: string;
  channel: "email" | "sms";
  recipient?: string | null;
  subject?: string | null;
  body?: string | null;
  status: "pending" | "sent" | "failed" | "skipped";
  provider?: string | null;
  error_message?: string | null;
  created_at: string;
}

const formatDate = (value?: string | null) => {
  if (!value) return "-";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "-" : date.toLocaleString();
};

export function NotificationsModule() {
  const { params, setParams, data, loading, refresh } = useList<NotificationLogRow>("/notifications", { page: 1, pageSize: 20 });
  const rows = data.data;
  const emailCount = rows.filter((row) => row.channel === "email").length;
  const smsCount = rows.filter((row) => row.channel === "sms").length;
  const failedCount = rows.filter((row) => row.status === "failed").length;

  const columns: Column<NotificationLogRow>[] = [
    {
      key: "subject",
      header: "Message",
      cell: (row) => (
        <div>
          <div className="font-medium">{row.subject || "Attendance alert"}</div>
          <div className="max-w-xl truncate text-xs text-muted-foreground">{row.body || row.error_message || "-"}</div>
        </div>
      ),
    },
    { key: "channel", header: "Channel", cell: (row) => <span className="capitalize">{row.channel}</span> },
    { key: "recipient", header: "Recipient", cell: (row) => row.recipient || "-" },
    { key: "provider", header: "Provider", cell: (row) => row.provider || "-" },
    { key: "status", header: "Status", cell: (row) => <StatusBadge value={row.status} /> },
    { key: "created_at", header: "Created", cell: (row) => <span className="text-muted-foreground">{formatDate(row.created_at)}</span> },
  ];

  return (
    <div>
      <PageHeader
        title="Notifications"
        description="Email and SMS delivery logs generated by attendance and college workflows."
        actions={<Button variant="outline" onClick={refresh}><RefreshCw className="mr-2 h-4 w-4" /> Refresh</Button>}
      />

      <div className="mb-6 grid gap-4 md:grid-cols-3">
        <StatCard label="Email Logs" value={emailCount} icon={Mail} accent="primary" />
        <StatCard label="SMS Logs" value={smsCount} icon={MessageSquare} accent="blue" />
        <StatCard label="Failed" value={failedCount} icon={Bell} accent="rose" />
      </div>

      <DataTable
        columns={columns}
        data={data}
        loading={loading}
        params={params}
        onParamsChange={setParams}
        searchPlaceholder="Search notifications..."
      />
    </div>
  );
}
