/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMenusRouteImport } from './routes/_app.menus'
import { Route as AppInstitutionsRouteImport } from './routes/_app.institutions'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsPermsRouteImport } from './routes/_app.settings.perms'
import { Route as AppSettingsMenusRouteImport } from './routes/_app.settings.menus'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMenusRoute = AppMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionsRoute = AppInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPermsRoute = AppSettingsPermsRouteImport.update({
  id: '/settings/perms',
  path: '/settings/perms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMenusRoute = AppSettingsMenusRouteImport.update({
  id: '/settings/menus',
  path: '/settings/menus',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees': typeof AppFeesRoute
  '/institutions': typeof AppInstitutionsRoute
  '/menus': typeof AppMenusRoute
  '/notifications': typeof AppNotificationsRoute
  '/organizations': typeof AppOrganizationsRoute
  '/roles': typeof AppRolesRoute
  '/staff': typeof AppStaffRoute
  '/students': typeof AppStudentsRoute
  '/users': typeof AppUsersRoute
  '/settings/menus': typeof AppSettingsMenusRoute
  '/settings/perms': typeof AppSettingsPermsRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees': typeof AppFeesRoute
  '/institutions': typeof AppInstitutionsRoute
  '/menus': typeof AppMenusRoute
  '/notifications': typeof AppNotificationsRoute
  '/organizations': typeof AppOrganizationsRoute
  '/roles': typeof AppRolesRoute
  '/staff': typeof AppStaffRoute
  '/students': typeof AppStudentsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/settings/menus': typeof AppSettingsMenusRoute
  '/settings/perms': typeof AppSettingsPermsRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/institutions': typeof AppInstitutionsRoute
  '/_app/menus': typeof AppMenusRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/menus': typeof AppSettingsMenusRoute
  '/_app/settings/perms': typeof AppSettingsPermsRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/fees'
    | '/institutions'
    | '/menus'
    | '/notifications'
    | '/organizations'
    | '/roles'
    | '/staff'
    | '/students'
    | '/users'
    | '/settings/menus'
    | '/settings/perms'
    | '/settings/roles'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/fees'
    | '/institutions'
    | '/menus'
    | '/notifications'
    | '/organizations'
    | '/roles'
    | '/staff'
    | '/students'
    | '/users'
    | '/'
    | '/settings/menus'
    | '/settings/perms'
    | '/settings/roles'
    | '/settings/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/fees'
    | '/_app/institutions'
    | '/_app/menus'
    | '/_app/notifications'
    | '/_app/organizations'
    | '/_app/roles'
    | '/_app/staff'
    | '/_app/students'
    | '/_app/users'
    | '/_app/'
    | '/_app/settings/menus'
    | '/_app/settings/perms'
    | '/_app/settings/roles'
    | '/_app/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menus': {
      id: '/_app/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AppMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutions': {
      id: '/_app/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof AppInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/perms': {
      id: '/_app/settings/perms'
      path: '/settings/perms'
      fullPath: '/settings/perms'
      preLoaderRoute: typeof AppSettingsPermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/menus': {
      id: '/_app/settings/menus'
      path: '/settings/menus'
      fullPath: '/settings/menus'
      preLoaderRoute: typeof AppSettingsMenusRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeesRoute: typeof AppFeesRoute
  AppInstitutionsRoute: typeof AppInstitutionsRoute
  AppMenusRoute: typeof AppMenusRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsMenusRoute: typeof AppSettingsMenusRoute
  AppSettingsPermsRoute: typeof AppSettingsPermsRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeesRoute: AppFeesRoute,
  AppInstitutionsRoute: AppInstitutionsRoute,
  AppMenusRoute: AppMenusRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppRolesRoute: AppRolesRoute,
  AppStaffRoute: AppStaffRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsMenusRoute: AppSettingsMenusRoute,
  AppSettingsPermsRoute: AppSettingsPermsRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
