/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMenusRouteImport } from './routes/_app.menus'
import { Route as AppInstitutionsRouteImport } from './routes/_app.institutions'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppStudentsIndexRouteImport } from './routes/_app.students.index'
import { Route as AppStudentsStatusRouteImport } from './routes/_app.students.status'
import { Route as AppStudentsRegistryRouteImport } from './routes/_app.students.registry'
import { Route as AppStudentsGuardiansRouteImport } from './routes/_app.students.guardians'
import { Route as AppStudentsDocumentsRouteImport } from './routes/_app.students.documents'
import { Route as AppStudentsAdmissionsRouteImport } from './routes/_app.students.admissions'
import { Route as AppStudentsAcademicRecordsRouteImport } from './routes/_app.students.academic-records'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsPermsRouteImport } from './routes/_app.settings.perms'
import { Route as AppSettingsMenusRouteImport } from './routes/_app.settings.menus'
import { Route as AppAcademicYearsRouteImport } from './routes/_app.academic.years'
import { Route as AppAcademicSubjectsRouteImport } from './routes/_app.academic.subjects'
import { Route as AppAcademicSectionsRouteImport } from './routes/_app.academic.sections'
import { Route as AppAcademicCoursesRouteImport } from './routes/_app.academic.courses'
import { Route as AppAcademicClassesRouteImport } from './routes/_app.academic.classes'
import { Route as AppAcademicBranchesRouteImport } from './routes/_app.academic.branches'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMenusRoute = AppMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionsRoute = AppInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsStatusRoute = AppStudentsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsRegistryRoute = AppStudentsRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsGuardiansRoute = AppStudentsGuardiansRouteImport.update({
  id: '/guardians',
  path: '/guardians',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsDocumentsRoute = AppStudentsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsAdmissionsRoute = AppStudentsAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppStudentsAcademicRecordsRoute =
  AppStudentsAcademicRecordsRouteImport.update({
    id: '/academic-records',
    path: '/academic-records',
    getParentRoute: () => AppStudentsRoute,
  } as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPermsRoute = AppSettingsPermsRouteImport.update({
  id: '/settings/perms',
  path: '/settings/perms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMenusRoute = AppSettingsMenusRouteImport.update({
  id: '/settings/menus',
  path: '/settings/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicYearsRoute = AppAcademicYearsRouteImport.update({
  id: '/academic/years',
  path: '/academic/years',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicSubjectsRoute = AppAcademicSubjectsRouteImport.update({
  id: '/academic/subjects',
  path: '/academic/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicSectionsRoute = AppAcademicSectionsRouteImport.update({
  id: '/academic/sections',
  path: '/academic/sections',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicCoursesRoute = AppAcademicCoursesRouteImport.update({
  id: '/academic/courses',
  path: '/academic/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicClassesRoute = AppAcademicClassesRouteImport.update({
  id: '/academic/classes',
  path: '/academic/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicBranchesRoute = AppAcademicBranchesRouteImport.update({
  id: '/academic/branches',
  path: '/academic/branches',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees': typeof AppFeesRoute
  '/institutions': typeof AppInstitutionsRoute
  '/menus': typeof AppMenusRoute
  '/notifications': typeof AppNotificationsRoute
  '/organizations': typeof AppOrganizationsRoute
  '/roles': typeof AppRolesRoute
  '/staff': typeof AppStaffRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/teachers': typeof AppTeachersRoute
  '/users': typeof AppUsersRoute
  '/academic/branches': typeof AppAcademicBranchesRoute
  '/academic/classes': typeof AppAcademicClassesRoute
  '/academic/courses': typeof AppAcademicCoursesRoute
  '/academic/sections': typeof AppAcademicSectionsRoute
  '/academic/subjects': typeof AppAcademicSubjectsRoute
  '/academic/years': typeof AppAcademicYearsRoute
  '/settings/menus': typeof AppSettingsMenusRoute
  '/settings/perms': typeof AppSettingsPermsRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/students/academic-records': typeof AppStudentsAcademicRecordsRoute
  '/students/admissions': typeof AppStudentsAdmissionsRoute
  '/students/documents': typeof AppStudentsDocumentsRoute
  '/students/guardians': typeof AppStudentsGuardiansRoute
  '/students/registry': typeof AppStudentsRegistryRoute
  '/students/status': typeof AppStudentsStatusRoute
  '/students/': typeof AppStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees': typeof AppFeesRoute
  '/institutions': typeof AppInstitutionsRoute
  '/menus': typeof AppMenusRoute
  '/notifications': typeof AppNotificationsRoute
  '/organizations': typeof AppOrganizationsRoute
  '/roles': typeof AppRolesRoute
  '/staff': typeof AppStaffRoute
  '/teachers': typeof AppTeachersRoute
  '/users': typeof AppUsersRoute
  '/academic/branches': typeof AppAcademicBranchesRoute
  '/academic/classes': typeof AppAcademicClassesRoute
  '/academic/courses': typeof AppAcademicCoursesRoute
  '/academic/sections': typeof AppAcademicSectionsRoute
  '/academic/subjects': typeof AppAcademicSubjectsRoute
  '/academic/years': typeof AppAcademicYearsRoute
  '/settings/menus': typeof AppSettingsMenusRoute
  '/settings/perms': typeof AppSettingsPermsRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/students/academic-records': typeof AppStudentsAcademicRecordsRoute
  '/students/admissions': typeof AppStudentsAdmissionsRoute
  '/students/documents': typeof AppStudentsDocumentsRoute
  '/students/guardians': typeof AppStudentsGuardiansRoute
  '/students/registry': typeof AppStudentsRegistryRoute
  '/students/status': typeof AppStudentsStatusRoute
  '/students': typeof AppStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/institutions': typeof AppInstitutionsRoute
  '/_app/menus': typeof AppMenusRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/academic/branches': typeof AppAcademicBranchesRoute
  '/_app/academic/classes': typeof AppAcademicClassesRoute
  '/_app/academic/courses': typeof AppAcademicCoursesRoute
  '/_app/academic/sections': typeof AppAcademicSectionsRoute
  '/_app/academic/subjects': typeof AppAcademicSubjectsRoute
  '/_app/academic/years': typeof AppAcademicYearsRoute
  '/_app/settings/menus': typeof AppSettingsMenusRoute
  '/_app/settings/perms': typeof AppSettingsPermsRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/students/academic-records': typeof AppStudentsAcademicRecordsRoute
  '/_app/students/admissions': typeof AppStudentsAdmissionsRoute
  '/_app/students/documents': typeof AppStudentsDocumentsRoute
  '/_app/students/guardians': typeof AppStudentsGuardiansRoute
  '/_app/students/registry': typeof AppStudentsRegistryRoute
  '/_app/students/status': typeof AppStudentsStatusRoute
  '/_app/students/': typeof AppStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/fees'
    | '/institutions'
    | '/menus'
    | '/notifications'
    | '/organizations'
    | '/roles'
    | '/staff'
    | '/students'
    | '/teachers'
    | '/users'
    | '/academic/branches'
    | '/academic/classes'
    | '/academic/courses'
    | '/academic/sections'
    | '/academic/subjects'
    | '/academic/years'
    | '/settings/menus'
    | '/settings/perms'
    | '/settings/roles'
    | '/settings/users'
    | '/students/academic-records'
    | '/students/admissions'
    | '/students/documents'
    | '/students/guardians'
    | '/students/registry'
    | '/students/status'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/fees'
    | '/institutions'
    | '/menus'
    | '/notifications'
    | '/organizations'
    | '/roles'
    | '/staff'
    | '/teachers'
    | '/users'
    | '/academic/branches'
    | '/academic/classes'
    | '/academic/courses'
    | '/academic/sections'
    | '/academic/subjects'
    | '/academic/years'
    | '/settings/menus'
    | '/settings/perms'
    | '/settings/roles'
    | '/settings/users'
    | '/students/academic-records'
    | '/students/admissions'
    | '/students/documents'
    | '/students/guardians'
    | '/students/registry'
    | '/students/status'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/fees'
    | '/_app/institutions'
    | '/_app/menus'
    | '/_app/notifications'
    | '/_app/organizations'
    | '/_app/roles'
    | '/_app/staff'
    | '/_app/students'
    | '/_app/teachers'
    | '/_app/users'
    | '/_app/academic/branches'
    | '/_app/academic/classes'
    | '/_app/academic/courses'
    | '/_app/academic/sections'
    | '/_app/academic/subjects'
    | '/_app/academic/years'
    | '/_app/settings/menus'
    | '/_app/settings/perms'
    | '/_app/settings/roles'
    | '/_app/settings/users'
    | '/_app/students/academic-records'
    | '/_app/students/admissions'
    | '/_app/students/documents'
    | '/_app/students/guardians'
    | '/_app/students/registry'
    | '/_app/students/status'
    | '/_app/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menus': {
      id: '/_app/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AppMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutions': {
      id: '/_app/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof AppInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/status': {
      id: '/_app/students/status'
      path: '/status'
      fullPath: '/students/status'
      preLoaderRoute: typeof AppStudentsStatusRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/registry': {
      id: '/_app/students/registry'
      path: '/registry'
      fullPath: '/students/registry'
      preLoaderRoute: typeof AppStudentsRegistryRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/guardians': {
      id: '/_app/students/guardians'
      path: '/guardians'
      fullPath: '/students/guardians'
      preLoaderRoute: typeof AppStudentsGuardiansRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/documents': {
      id: '/_app/students/documents'
      path: '/documents'
      fullPath: '/students/documents'
      preLoaderRoute: typeof AppStudentsDocumentsRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/admissions': {
      id: '/_app/students/admissions'
      path: '/admissions'
      fullPath: '/students/admissions'
      preLoaderRoute: typeof AppStudentsAdmissionsRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/students/academic-records': {
      id: '/_app/students/academic-records'
      path: '/academic-records'
      fullPath: '/students/academic-records'
      preLoaderRoute: typeof AppStudentsAcademicRecordsRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/perms': {
      id: '/_app/settings/perms'
      path: '/settings/perms'
      fullPath: '/settings/perms'
      preLoaderRoute: typeof AppSettingsPermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/menus': {
      id: '/_app/settings/menus'
      path: '/settings/menus'
      fullPath: '/settings/menus'
      preLoaderRoute: typeof AppSettingsMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/years': {
      id: '/_app/academic/years'
      path: '/academic/years'
      fullPath: '/academic/years'
      preLoaderRoute: typeof AppAcademicYearsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/subjects': {
      id: '/_app/academic/subjects'
      path: '/academic/subjects'
      fullPath: '/academic/subjects'
      preLoaderRoute: typeof AppAcademicSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/sections': {
      id: '/_app/academic/sections'
      path: '/academic/sections'
      fullPath: '/academic/sections'
      preLoaderRoute: typeof AppAcademicSectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/courses': {
      id: '/_app/academic/courses'
      path: '/academic/courses'
      fullPath: '/academic/courses'
      preLoaderRoute: typeof AppAcademicCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/classes': {
      id: '/_app/academic/classes'
      path: '/academic/classes'
      fullPath: '/academic/classes'
      preLoaderRoute: typeof AppAcademicClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/branches': {
      id: '/_app/academic/branches'
      path: '/academic/branches'
      fullPath: '/academic/branches'
      preLoaderRoute: typeof AppAcademicBranchesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsAcademicRecordsRoute: typeof AppStudentsAcademicRecordsRoute
  AppStudentsAdmissionsRoute: typeof AppStudentsAdmissionsRoute
  AppStudentsDocumentsRoute: typeof AppStudentsDocumentsRoute
  AppStudentsGuardiansRoute: typeof AppStudentsGuardiansRoute
  AppStudentsRegistryRoute: typeof AppStudentsRegistryRoute
  AppStudentsStatusRoute: typeof AppStudentsStatusRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsAcademicRecordsRoute: AppStudentsAcademicRecordsRoute,
  AppStudentsAdmissionsRoute: AppStudentsAdmissionsRoute,
  AppStudentsDocumentsRoute: AppStudentsDocumentsRoute,
  AppStudentsGuardiansRoute: AppStudentsGuardiansRoute,
  AppStudentsRegistryRoute: AppStudentsRegistryRoute,
  AppStudentsStatusRoute: AppStudentsStatusRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeesRoute: typeof AppFeesRoute
  AppInstitutionsRoute: typeof AppInstitutionsRoute
  AppMenusRoute: typeof AppMenusRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppTeachersRoute: typeof AppTeachersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppAcademicBranchesRoute: typeof AppAcademicBranchesRoute
  AppAcademicClassesRoute: typeof AppAcademicClassesRoute
  AppAcademicCoursesRoute: typeof AppAcademicCoursesRoute
  AppAcademicSectionsRoute: typeof AppAcademicSectionsRoute
  AppAcademicSubjectsRoute: typeof AppAcademicSubjectsRoute
  AppAcademicYearsRoute: typeof AppAcademicYearsRoute
  AppSettingsMenusRoute: typeof AppSettingsMenusRoute
  AppSettingsPermsRoute: typeof AppSettingsPermsRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeesRoute: AppFeesRoute,
  AppInstitutionsRoute: AppInstitutionsRoute,
  AppMenusRoute: AppMenusRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppRolesRoute: AppRolesRoute,
  AppStaffRoute: AppStaffRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppTeachersRoute: AppTeachersRoute,
  AppUsersRoute: AppUsersRoute,
  AppAcademicBranchesRoute: AppAcademicBranchesRoute,
  AppAcademicClassesRoute: AppAcademicClassesRoute,
  AppAcademicCoursesRoute: AppAcademicCoursesRoute,
  AppAcademicSectionsRoute: AppAcademicSectionsRoute,
  AppAcademicSubjectsRoute: AppAcademicSubjectsRoute,
  AppAcademicYearsRoute: AppAcademicYearsRoute,
  AppSettingsMenusRoute: AppSettingsMenusRoute,
  AppSettingsPermsRoute: AppSettingsPermsRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
